osx_image: xcode7.1
language: swift

script: 
- xctool -project ImageViewer.xcodeproj -scheme ImageViewer -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.1,name=iPhone 6' ONLY_ACTIVE_ARCH=NO clean build
- xctool -project ImageViewer.xcodeproj -scheme ImageViewer -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=8.4,name=iPhone 6' ONLY_ACTIVE_ARCH=NO clean build

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool